name: KRX ETF Test

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test system
        run: echo "KRX ETF Analyzer is working"
